# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  gollum:
    types: [created, edited, deleted]
  schedule:
      - cron: '0 0 1 * *'
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    types:
      - opened
  issue_comment:
    branches: [ master ]
    types: [created, deleted, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          TIME: ${{ steps.date.outputs.date }}
        run: echo Hello, world! Today is $TIME

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
